In [1]:
import numpy as np

In [2]:
a = np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'in

In [8]:
a = np.random.randint(1, 10, (2,4))
b = np.random.randint(1, 10, (2,4))

In [9]:
a

array([[3, 6, 3, 5],
       [8, 8, 1, 1]])

In [10]:
b

array([[2, 1, 3, 8],
       [8, 9, 4, 3]])

In [11]:
a + b

array([[ 5,  7,  6, 13],
       [16, 17,  5,  4]])

In [12]:
a = np.random.randint(1, 10, (3,6))
b = np.random.randint(1, 10, (2,4))

In [13]:
a + b

ValueError: operands could not be broadcast together with shapes (3,6) (2,4) 

In [17]:
a = np.random.randint(1, 10, (4))
b = np.random.randint(1, 10, (2,4))

In [18]:
a

array([4, 7, 2, 8])

In [19]:
b

array([[1, 5, 3, 8],
       [1, 3, 9, 3]])

In [20]:
a + b

array([[ 5, 12,  5, 16],
       [ 5, 10, 11, 11]])

In [21]:
a = np.random.randint(1, 10, (4,2))
b = np.random.randint(1, 10, (2,4))

In [22]:
a

array([[9, 3],
       [4, 9],
       [5, 8],
       [1, 3]])

In [23]:
b

array([[7, 3, 7, 8],
       [9, 5, 8, 9]])

In [24]:
a + b

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [25]:
a = np.random.randint(1, 10, (2,1))
b = np.random.randint(1, 10, (2,4))

In [26]:
a

array([[5],
       [1]])

In [27]:
b

array([[9, 7, 3, 5],
       [6, 4, 5, 8]])

In [28]:
a + b

array([[14, 12,  8, 10],
       [ 7,  5,  6,  9]])

In [29]:
a = np.random.randint(1, 10, (300, 2,1))
b = np.random.randint(1, 10, (2,4))

In [30]:
a

array([[[9],
        [9]],

       [[6],
        [7]],

       [[6],
        [4]],

       [[7],
        [7]],

       [[8],
        [6]],

       [[8],
        [9]],

       [[6],
        [4]],

       [[1],
        [5]],

       [[6],
        [3]],

       [[5],
        [4]],

       [[9],
        [9]],

       [[8],
        [8]],

       [[6],
        [5]],

       [[4],
        [3]],

       [[5],
        [7]],

       [[4],
        [4]],

       [[4],
        [4]],

       [[5],
        [6]],

       [[2],
        [1]],

       [[8],
        [6]],

       [[1],
        [9]],

       [[2],
        [3]],

       [[9],
        [6]],

       [[9],
        [5]],

       [[8],
        [8]],

       [[6],
        [2]],

       [[8],
        [5]],

       [[9],
        [3]],

       [[5],
        [7]],

       [[1],
        [9]],

       [[5],
        [4]],

       [[5],
        [5]],

       [[3],
        [3]],

       [[6],
        [2]],

       [[4],
        [1]],

       [[4],
       

In [31]:
b

array([[2, 8, 6, 7],
       [7, 6, 6, 3]])

In [32]:
a + b

array([[[11, 17, 15, 16],
        [16, 15, 15, 12]],

       [[ 8, 14, 12, 13],
        [14, 13, 13, 10]],

       [[ 8, 14, 12, 13],
        [11, 10, 10,  7]],

       ...,

       [[ 4, 10,  8,  9],
        [11, 10, 10,  7]],

       [[ 8, 14, 12, 13],
        [11, 10, 10,  7]],

       [[10, 16, 14, 15],
        [ 8,  7,  7,  4]]])

In [34]:
# Rules of Broadcasting
# Rule 1 : Shape should be same, start checking from right traverse towards left
# Rule 2 : If Shape has got 1, then it will definitely broadcast