In [1]:
a = 6

In [2]:
a = 8

In [3]:
import numpy as np

In [4]:
iterable = [3, 6, 7, 11]

In [5]:
n = np.array(iterable)

In [6]:
type(n)

numpy.ndarray

In [24]:
twod = np.array([[1, 2, 5], [3, 4, 7]])

In [27]:
twod.shape

(2, 3)

In [10]:
twod = np.array([[1, 2],[3, 4]])

In [11]:
twod

array([[1, 2],
       [3, 4]])

In [12]:
twod = np.array([[1, 2],[3, 4, 5]])

In [14]:
twod

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [15]:
hetero = np.array([1, 2, 3, 4, "77"])

In [16]:
hetero

array(['1', '2', '3', '4', '77'], dtype='<U11')

In [18]:
n.shape

(4,)

In [28]:
list(range(9, 16))

[9, 10, 11, 12, 13, 14, 15]

In [29]:
list(range(9, 16, 2))

[9, 11, 13, 15]

In [31]:
np.arange(7, 16)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
type(np.arange(7, 16))

numpy.ndarray

In [33]:
np.arange(7, 16 , 2)

array([ 7,  9, 11, 13, 15])

In [34]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distan

In [36]:
li = np.arange(40).reshape(8, 5)

In [38]:
li

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [37]:
li.shape

(8, 5)

In [39]:
li.ndim

2

In [40]:
arr1 = np.arange(40)

In [41]:
arr2 = arr1.reshape(8, 5)

In [42]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [43]:
arr1[0] = 1000

In [44]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [45]:
arr1 is arr2

False

In [46]:
arr1.itemsize

4